import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import SmoothScrolling from "@/providers/smooth-scrolling";
import { Header } from "@/components/header";

const syne = Syne({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrolling>
      <html lang="en">
        <body className={syne.className}>
          <Header />
          h1
          {children}
          </body>
      </html>
    </SmoothScrolling>
  );
}
