import type { Metadata } from "next";
import { Syne } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import SmoothScrolling from "@/providers/smooth-scrolling";
import { Header } from "@/components/header";
import localFont from "next/font/local";
import { Cursor } from "@/components/cursor";

const syne = Syne({ subsets: ["latin"], display: "swap", variable: "--syne_font" });
const gallery = localFont({ src: "../assets/fonts/gallerymodern.woff2", variable: "--gallery_modern" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SmoothScrolling>
      <html lang="en">
        <body className={`${syne.className} ${syne.variable} ${gallery.variable}`}>
          <Cursor />
          <Header />
          {children}
        </body>
      </html>
    </SmoothScrolling>
  );
}
